### ISSUE TITLE
商品情報のデータセット

### ISSUE THREAD

**Issue by d-mato** [AnguillaJaponica/elasticsearch-exercise#4]
サクッと開発できるように seed として用意したい。
個別にデータ登録するは面倒なので、適当なオープンデータがあれば使いたい。
もしくは適当なECサイトをスクレイピングしても良い。

**Comment by AnguillaJaponica** [comment]
[satofull_products.csv](https://github.com/AnguillaJaponica/elasticsearch-exercise/files/12908934/satofull_products.csv)
![image](https://github.com/AnguillaJaponica/elasticsearch-exercise/assets/47109605/11985755-cb26-447f-ba23-fe39e4620a1f)
シンプルにhttps://www.satofull.jp/ からこんな感じで商品データ取ってきました。1万件弱くらいあります!

**Comment by d-mato** [comment]
めっちゃ良い！
